Fix a compile warning thrown by gcc-9
The warning is 
```
evhttp_request.cc:260:29: error: null argument where non-null required (argument 2) [-Werror=nonnull]
  260 |     if (content_encoding != nullptr) {
      |                             ^~~~~~~
```
 GetRequestHeader will always return a valid string_view, there is no need to explicitly compare it to nullptr.